### ISSUE TITLE
Kustomize Plugin

### ISSUE THREAD

**Issue by runderwoodcr14** [isindir/sops-secrets-operator#103]
Hello,
This is not really an issue but more question, I've been using sops-secrets-operator for some days and seems to fit pretty well my needs to decrypt sops secrets, however I can't seem to find a way to use it with kustomize, I've been looking on the source code and wondered if anyone has already successfully created a plugin to be use with kustomize, I looked in the issues and can't find anything related, I've tried to use other kustomize plugins for sops but still I get this error:

`Error: loading generator plugins: expected file with Go object code at: /root/.config/kustomize/plugin/isindir.github.com/v1alpha3/sopssecret/SopsSecret.so`

So any hints and help on this topic its greatly appreciated.

**Comment by isindir** [comment]
@runderwoodcr14 - `sops-secrets-operator` is supposed to be running inside the cluster and not as `kustomize` plugin. The supported way to deploy it is via `helm` chart. The workflow is fairly simple:
* deploy it in your cluster
* create yaml file for SopsSecret custom resource
* encrypt it using `sops` command
* apply it to the cluster - sops operator will create kubernetes secrets from sopssecret

**Comment by runderwoodcr14** [comment]
I have the operator running in the cluster, I can create the SopsSecret custom resource and I can apply it using kubectl, and I  installed it using the helm chart, however I use kustomize to deploy applications into k8s together with argocd.
Indeed I have ksops in the cluster, however ksops uses a different custom resource, so I though maybe it was possible to use sops-secrets-operator with SopsSecret custom resource with kustomize, so the idea is to have a single custom resource that could work for both, maybe is out of scope, I was just wondering if someone faced the same challenge and found a solution, with ArgoCD as you may know we use GitOps, if I use ksops I will not need then SopsSecret custom resource.
Not sure if that clarifies better my idea and scenario.

Thanks for your reply.

**Comment by isindir** [comment]
I'm applying SopsSecrets in my homelab using flux2 and kustomize, you just need to include your sopssecret file to deployment in git repository (I've not used argocd myself).
For example:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-system
resources:
  - oauth2-proxy-secrets.sops.enc.yaml
  - ../../base/18-oauth2-proxy
patchesStrategicMerge:
  - oauth2-proxy.helmrelease-patch.yaml
```

The `kustomize` plugin and sops operator are 2 completely different ways of using `sops`. SopsSecret can be applied via CI/CD or GitOps using kubectl or kustomize commands. Also I don't know how `kustomize` plugins are working but unlikely you can use both in one workflow, you probably can use these in the same cluster using different workflows, but I don't see good reasons - why.

**Comment by runderwoodcr14** [comment]
@isindir thanks for your reply, I will check again using this approach.
I think its a matter of preferences, I chose `kustomize` over `helm` because is natively supported by k8s and kubectl and requires no third party software, plus is easier for developers to just go with manifest `yaml's` than creating the charts and templates, I think both have their pros and cons, now related with the status of the deployments, you can get that from ArgoCD, it really simplifies the management of hundreds and thousands of deployments to one or `n` clusters, very useful when you have multiple cluster with multiple environments and want to ensure GitOps and DevOps good practices and ensuring that you can have consistent Deployments.
Yet again, thanks for your time, I think then this can be closed.
