### ISSUE TITLE
In Kubernetes, how to create a sops secret from a binary file ? 

### ISSUE THREAD

**Issue by HugoRh** [isindir/sops-secrets-operator#134]
Hi !

I'm struggling with that one, all my secrets are maintained with SOPS operator, recently I had to integrate a binary file as a secret but I can't seem to make it work...
I can update in place the binary file but I can't integrate it in a template...
Anyone has a method to achieve that ?

Thanks !!

**Comment by erikzele** [comment]
@HugoRh potentially the easiest solution is to base64 encode binary and then create secret from the resulting string. Your application would need to decode it at runtime.

**Comment by erikzele** [comment]
closing issue

**Comment by isindir** [comment]
closing issue
