### ISSUE TITLE
Unable to create secrets with a custom type

### ISSUE THREAD

**Issue by StefanVanDyck** [isindir/sops-secrets-operator#141]
Hello,

Loving this operator, works great on our clusters.
I was just having some trouble creating a secret to mount our samba/cifs shared network drive.
It requires a secret with type _"fstab/cifs"_.

Unfortunately the operator only seems to allow the standard k8s types.
Not sure if it is best-practice to do things this way, but I did find this on the k8s docs:

> You can define and use your own Secret type by assigning a non-empty string as the type value for a Secret object (an empty string is treated as an Opaque type).

> Kubernetes doesn't impose any constraints on the type name. However, if you are using one of the built-in types, you must meet all the requirements defined for that type.

Anyway, I played around with some changes locally and I think I made the necessary changes to make it work for me.
I added some tests to validate, but I am by no means an experienced Go developer.

I'll try to PR/fork my changes so you can have a look at them.

Let me know if you have any questions / I can do anything else.

Thanks for the great work!

**Comment by isindir** [comment]
I'll have a closer look at the end of the week

**Comment by StefanDeltaRay** [comment]
I tried out the new version and it seems to work.
Thanks!

**Comment by isindir** [comment]
Hi @StefanDeltaRay, thanks again for contributing!
