### ISSUE TITLE
Github Pages returns 404

### ISSUE THREAD

**Issue by AdrianAntunez** [isindir/sops-secrets-operator#166]
Hi there!

I tried to go to https://isindir.github.io/sops-secrets-operator but I've found a 404 file not found:

![Screenshot 2024-02-08 at 16 33 18](https://github.com/isindir/sops-secrets-operator/assets/1443326/545b0bd4-aaaf-41cf-9821-a94cd75918f9)

Might be related to today's release. JFYI

**Comment by isindir** [comment]
@AdrianAntunez Have you seen any content on the mentioned address in the past ? I'm not using Github pages for web page or documentation, I'm using it as helm chart repository, ant it is available as expected:
https://isindir.github.io/sops-secrets-operator/index.yaml

**Comment by AdrianAntunez** [comment]
Oh right, then that's the reason. I tried to follow the link from https://github.com/isindir/sops-secrets-operator/deployments/github-pages and then I found this 404.
Thx for explaining it!
