### ISSUE TITLE
There is no way to add labels to servicemonitor in helm

### ISSUE THREAD

**Issue by slimes28** [isindir/sops-secrets-operator#186]
Hello,
There is no way to add labels to servicemonitor in helm. 
Here is PR to fix it: https://github.com/isindir/sops-secrets-operator/pull/185

**Comment by isindir** [comment]
@slimes28 , thank you for contributing. 

* Please install all tools specified in `.tool-versions` file using https://asdf-vm.com/
* Please install latest helm `unittest` plugin - https://github.com/helm-unittest/helm-unittest
* Run `make test-helm`, fix issues and add new tests related to your change in `chart/helm3/sops-secrets-operator/tests/monitor_test.yaml`. 
* Please update README.md Versioning section top line of the table.
* run `make package-helm`.

Thanks

**Comment by slimes28** [comment]
@isindir Updated PR

**Comment by isindir** [comment]
merged
