### ISSUE TITLE
Overly permissive cluster role?

### ISSUE THREAD

**Issue by aywrite** [isindir/sops-secrets-operator#24]
The current cluster role allows unrestricted access to resources such as pods, services, pvc, events, secrets, configmaps and deployments among others. While I understand the need to create and modify secrets in all namespaces I was wondering if a less permissive cluster role would be possible, particularly for resources like pods and deployments etc?

This could be in the form of restricting access to the minimum required verbs for each of these resources or perhaps creating a separate role & role binding to namespace some of the permissions which don't need to be cluster-wide.

**Comment by isindir** [comment]
I agree the role can become more restrictive. Any help in testing it greatly appreciated. At the moment I have only access to local development environment where I can deploy and test with gpg keys, which perhaps in many cases may be helpful, but not enough. Also current testing is not covering real in cluster installation, I'm running binary standalone using admin permissions.

**Comment by isindir** [comment]
@aywrite can you please test the helm chart package which is on featore branch of #26 . I have tested in local cluster with pgp, but I'm not one hunderd percent sure it will work with AWS or GCP, if you have AWS setup, that would be superhelpful.
Thanks

**Comment by aywrite** [comment]
@isindir thanks, yeah I will test with AWS sometime this week.

**Comment by aywrite** [comment]
@isindir From my testing on AWS (only pre-production) I haven't seen any issues

**Comment by isindir** [comment]
@aywrite , Thanks - I'll rebase and merge
