### ISSUE TITLE
Encrypted regex instead of suffix?

### ISSUE THREAD

**Issue by albertrdixon** [isindir/sops-secrets-operator#27]
It would be nice to have only the secret data fields encrypted, so secret names and annotations/labels can be easily diff'ed and verified.

Possible to use `encrypted_regex` in place of `encrypted_suffix` when encrypting files?

```.sops.yaml
# .sops.yaml
creation_rules:
  - path_regex: sops-secret.yaml$
    encrypted_regex: ^(data|stringData)$
    kms: arn:aws:...
```

**Comment by isindir** [comment]
@albertrdixon , I think if both can be combined (don't know from the top of my head) - than quite likely it is possible already. Otherwise that would need some redesign of the application logic as well as api version change. I'll check if 1st option is possible.

**Comment by albertrdixon** [comment]
That's a good point, not sure if they can be combined. Should be easy enough to test it out, I'll try also.

**Comment by albertrdixon** [comment]
Nah, looks like 1 or the other

```
❯ sops -e -i secret.yaml 
error loading config: cannot use more than one of encrypted_suffix, unencrypted_suffix, or encrypted_regex for the same rule
```

**Comment by isindir** [comment]
Thank you for help, I need time to think about 2nd option.

**Comment by isindir** [comment]
@albertrdixon apologies, I won't implement that. If you can help in doing, PRs are appreciated.

**Comment by isindir** [comment]
closing

**Comment by netaskd1** [comment]
@isindir `encrypted_regex` looks more powerful then `encrypted_suffix`. If it's hard to add `encrypted_regex`, could you just replace `encrypted_suffix` to `encrypted_regex`? `encrypted_regex` is more new feature then `encrypted_suffix` in sops, and can cover all cases that needs in encription fields. Exactly with this change and setting `encrypted_regex: '^(data)$'` we can use SopsSecret config in helm chart with templating `spec.secretTemplates.name`

**Comment by isindir** [comment]
@sekko27 and @netaskd1 - thanks for raising this issue once again. Now closing this issue.

**Comment by isindir** [comment]
reopened issue again, related to https://github.com/rancher/fleet/issues/144#issuecomment-785889778

**Comment by isindir** [comment]
can we please move this discussion to https://github.com/isindir/sops-secrets-operator/issues/27 , I have just re-opened it.
I think we have 2 issues here, one breaking and one nonbreaking:
* Breaking:
```
  - name: file-test
      data:
        some-file.txt: ...
```
> I think identation is broken here, should be like:
```
  - name: file-test
    data:
      some-file.txt: ...
```
* Nonbreaking: `^(data|stringData)$` does not make much sense in case of `SopsSecret` as `stringData` is k8s `Secret` specific field, not `SopsSecret` specific field, so the regex could be just: `^(data)$`.

**Comment by mumblez** [comment]
Hi @isindir 

I also tested by hand editing to fix the identation (and removed `stringData` from `.sops.yaml`) , same result unfortunately.

**Comment by isindir** [comment]
@mumblez I'm not sure if that is going to help, but can you please try to update CRD on the cluster with latest CRD ?
Also I don't know what fleet does exactly, from visual docs skim - it seems that it replicates resources from single cluster to children clusters ? if that is the case - could you please check if the resulting `sops` resource is same as original. Also the above error message does not look like originated from `sops-secrets-operator`, but `fleet-controller` - which perhaps tries to decrypt `sops` resource itself. In this case I'd suggest to try encrypt plain k8s secret and apply it with `fleet` and see how it behaves.

**Comment by isindir** [comment]
@mumblez What I'd suggest to check as well - is it possible to configure `fleet` not to use `sops` and then see how `sops` secrets are operated. I suspect `fleet` tries or even decrypts, where `sops-secrets-operator` only works with encrypted `SopsSecrets`. That means one or another should be disabled to avoid conflicts.

**Comment by mumblez** [comment]
sure, I suspected the issue was with fleet, your operator works as expected, but fleet has some logic to incercept `sops` resources but there's no way (currently) to configure this, I've mentioned the commit in the other ticket. Thanks for your help

**Comment by isindir** [comment]
Closing, looks like `fleet` is performing encryption itself - which is not related to `sops-secrets-operator`.
