### ISSUE TITLE
Advice: how to deploy SopsSecret resource with helm

### ISSUE THREAD

**Issue by mumblez** [isindir/sops-secrets-operator#33]
Hi,

Just wondering if you can help advise how I may be able to deploy 'SopsSecret' kind resource from other projects / helm charts.

In helm I get:

```sh
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "SopsSecret" in version "isindir.github.com/v1alpha2"
helm.go:81: [debug] unable to recognize "": no matches for kind "SopsSecret" in version "isindir.github.com/v1alpha2"
```

I was hoping I can just bootstrap the clusters and then use helm to package up secrets per project.
Maybe I'm going about this the wrong way, could you help advise?

Many Thanks

**Comment by isindir** [comment]
Hi @mumblez , 

are you using helm v2 or helm v3 ?

Helm chart v3 by default will install crd. For helm v2 you'd need to install it before installing the chart using something like (assuming repository is cloned already in to sops-secrets-operator):

```bash
kubectl apply -f sops-secrets-operator/config/crd/bases/isindir.github.com_sopssecrets.yaml
```

**Comment by mumblez** [comment]
Thanks @isindir 
Happy to close this :)
