### ISSUE TITLE
Add the ability to specify extra environment to the Deployment

### ISSUE THREAD

**Issue by gozer** [isindir/sops-secrets-operator#39]
The solution is generic, but the main reason I ran into for wanting/needing
it was the ability to make this work in EKS with IAM authentication.

Due to a bug somewhere in go-aws-sdk, one needs to set AWS_SDK_LOAD_CONFIG=1
to allow for the magical EKS/IAM authentication to work correctly.

**Comment by isindir** [comment]
@gozer Thanks for the contribution! I'll refactor PR a bit, so the oringinal will be closed without mergening.
