### ISSUE TITLE
Question - which version of upstream sops?

### ISSUE THREAD

**Issue by domhdp** [isindir/sops-secrets-operator#43]
Hi there, the README states that the `enc` field is not used/managed due to the way Kubernetes manages objects.

> sops-secrets-operator is not using standard sops library decryption interface function, modified upstream function is used to decrypt data which ignores enc signature field in sops metadata. This is due to the fact that when Kubernetes resource is applied it is always mutated by Kubernetes, for example resource version is generated and added to the resource. But any mutation invalidates sops metadata enc field and standard decryption function fails.

Is this still the case? If so, can you please provide the link of the modified upstream function?

**Comment by isindir** [comment]
Hi @domhdp , that is in controller code: https://github.com/isindir/sops-secrets-operator/blob/master/controllers/sopssecret_controller.go#L376

**Comment by domhdp** [comment]
Great thanks for that. Are you monitoring the upstream function? How foes the custom function stay up to date with the upstream version?
________________________________

**Comment by isindir** [comment]
The original function is described here and you can check the code as well, it is pretty much the same (may be a bit more decomposed) as it was when I copied it:

https://github.com/mozilla/sops#12development-branch
(see: To use sops as a library, take a look at the decrypt package.)
->
https://godoc.org/go.mozilla.org/sops/v3/decrypt#Data
->
https://github.com/mozilla/sops/blob/master/decrypt/decrypt.go#L73

**Comment by domhdp** [comment]
@isindir Thanks for that. I think it would be better if `IgnoreMAC` was included in the upstream external API of `mozilla/sops`, in a similar way to

https://github.com/mozilla/sops/blob/38b25bd449619e1d6da20e637702f7c73203aa44/cmd/sops/common/common.go#L92

Then there would be no need to maintain the custom function... is that right?

**Comment by domhdp** [comment]
I have created an upstream issue here 
https://github.com/mozilla/sops/issues/783

**Comment by isindir** [comment]
I think it is not going to happen based on the upstream project answer. Closing this issue.
