### ISSUE TITLE
error in test-connection pod 

### ISSUE THREAD

**Issue by yogeek** [isindir/sops-secrets-operator#68]
When deploying the operator from the chart with helm 3 :
```
helm template sops-secrets-operator sops/sops-secrets-operator  --namespace=${SOPS_NAMESPACE}  --set image.tag=0.2.0
```

a pod called `sops-secrets-operator-test-connection` is created from [this template](./chart/helm3/sops-secrets-operator/tests/operator_test.yaml) but always failed because it is base on a [busybox image](https://github.com/isindir/sops-secrets-operator/blob/master/chart/helm3/sops-secrets-operator/templates/tests/test-connection.yaml#L13) and launches the `kubectl` binary which is missing.

Is this test is meant to work as is ... ?

Apparently, one can pass the `--no-hooks` option to skip deploying the templates located in the tests folder.
Do you think the installation instruction could be updated with this information ?

```
helm template sops-secrets-operator sops/sops-secrets-operator  --namespace=${SOPS_NAMESPACE}  --set image.tag=0.2.0 --no-hooks
```

**Comment by isindir** [comment]
Hi @yogeek , latest version of chart does not suppport that old version of image, I'd suggest to migrate your deployment to the latest helm chart/image. From the version you mentioned API is changed slightly, so you'd need to change your sops secrets to upgrade.

**Comment by yogeek** [comment]
Helloe @isindir , what do you mean by `old version of image` ? I took the default version set by the [values.yaml](https://github.com/isindir/sops-secrets-operator/blob/master/chart/helm3/sops-secrets-operator/values.yaml#L15) : `0.2.0` (which s also the latest release in github). 
Can you be more specific please ?

**Comment by isindir** [comment]
sorry - mixed it with `0.0.2`...

**Comment by isindir** [comment]
The files in `tests` directory are only meaningful with helm plugin from https://github.com/quintush/helm-unittest , I'll add these files to `.helmignore`, so these are not packaged together with chart. Thanks for reporting. In addition see:

* https://github.com/isindir/sops-secrets-operator/blob/master/.circleci/config.yml#L190
* https://github.com/isindir/sops-secrets-operator/blob/master/.circleci/config.yml#L254
* https://github.com/isindir/sops-secrets-operator/blob/master/Makefile#L72
* https://github.com/isindir/sops-secrets-operator/blob/master/chart/helm3/sops-secrets-operator/Makefile#L32

I'll repackage helm chart tonight.

**Comment by isindir** [comment]
Hello @yogeek , I removed breaking test suite - it was pretty useless anyway, I could add RBAC templates to it, but then rbac resources stayed in the namespace even after test has finished. And checking if pods are running is not extremely useful anyway. Could you please re-test ?

**Comment by isindir** [comment]
closing
