### ISSUE TITLE
Document safe upgrade procedure between different versions of CRD API/sops-secrets-operator

### ISSUE THREAD

**Issue by isindir** [isindir/sops-secrets-operator#78]
Document safe procedure of upgrading from `sops-secrets-operator` api version `v1alpha1` to `v1alpha3` for example, so that there is no downtime and secrets are not deleted. This will be quite general guidance, specifics will be up to the reader - the procedure was tested to migrade from 0.0.9 to 0.3.0 on kind cluster using AWS credentials only.

**Comment by isindir** [comment]
@travisghansen , you may be interested in this - comming soon.

**Comment by travisghansen** [comment]
Awesome! The other ticket is still on my list (been really busy the last couple weeks) but if you’ve got something coming I’ll sit tight.

I’m in the early stages of usage but even where I’m at it would be a bit painful to disrupt the existing assets so this is great news!

**Comment by isindir** [comment]
@travisghansen can you please review the document which can be found on PR here:

https://github.com/isindir/sops-secrets-operator/tree/add_api_migration_example/docs/api_upgrade_example

Does it make sense or how can I improve to make more readable ?

**Comment by travisghansen** [comment]
Yeah I just reviewed and the doc seems clear enough. I’ve got it running across a fleet of clusters and those are managed via gitops so many things are automated, I haven’t tried yet but it seems like I could get myself in a bad state if not super careful. I can try it out on a cluster and see how things go.

I’m not super familiar with managing the lifecycle of crds but how difficult would it be to add conversion hooks? In the long term I’ll need something more sane to handle the upgrades I think. I’m happy to help (although my go skills are quite limited).

**Comment by isindir** [comment]
From [kubebuilder multiversion tutorial](https://book.kubebuilder.io/multiversion-tutorial/tutorial.html) I'd think I simply can't re-introduce conversion webhook to older versions, unless applying new CRD and upgrading operator with webhook in one go can do it. Please feel free to raise another issue for the feature, but it needs more time to build I guess. I'm closing this Issue.

**Comment by travisghansen** [comment]
Sounds good thanks for the consideration! I'll create a new issue.
