### ISSUE TITLE
support for conversion hooks to ease upgrade process between crd versions

### ISSUE THREAD

**Issue by travisghansen** [isindir/sops-secrets-operator#82]
I run this operator (thanks, it's great!) as a fairly integral part of the over-arching process to manage a fleet of clusters covering various environments (dev/test/prod/etc). Most of the cluster creation is automated and the ongoing maintenance is automated by gitops (`ArgoCD` atm). Moving between CRD versions will be quite painful without a seamless experience (I do recognize it's currently an alpha version of the CRD so while it would be great to support this for the existing versions, it's more generally about the longer term play) for not only the cluster admins but also the various groups/users that install apps/etc to the clusters.

For example I have several teams deploying disperse apps (most of them via gitops as well) and trying to coordinate the upgrading of all their assets in git/etc will prove quite difficult.

Thanks!

**Comment by isindir** [comment]
I'm playing with multiversion configuration and I think the main difficulty can be encryption/decryption itself. CRs are stored as is after being encrypted, but conversion webhook will brake current structure and worse than kubernetes, when it applies extra metadata fields. Conversion webhook must move elements of the spec around, for multiple versions into hub version. All versions which I had so far changed significantly, which means serious data reshuffling. Multi-version CRD can store only one version in k8s etcd, so conversion of all the versions into one version is a must, but at the same time it may brake decryption. I'll definetely play more with my controller, but it feels like this may not be possible.

**Comment by isindir** [comment]
I've tried with `sops` tool to mimic the above behavior:
* yaml file created:
```
spec:
  data_template:
    field1: abc
    field2: cde
```
* encrypt the file using `sops -e` and `--encrypted-suffix _template`
* I can decrypt with `sops -d` new file
* **experiment 1:** swap 2 lines - `field1` and `field2` and try to decrypt, only works with `sops -d --ignore-mac`
* **experiment 2:** try to create new file where I change `data_template` to `dataTemplate` and in `sops:` secrion change `encrypted_suffix: _template` to `encrypted_suffix: Template`
  * decryption with `sops -d --ignore-mac` fails
* **experiment 3:** try to rename `field1` to `field3` and `field2` to `field4`
  * decryption with `sops -d --ignore-mac` fails
* **experiment 4:** try to add new field `field3: qqq` under `data_template:`
  * decryption with fails
* **experiment 5:** try to add new field `field3: qqq` under `spec:`
  * decryption with successful (new data field outside of the encrypted tree)

That means any mutation of data which was part of the original file and part of the encrypted subtree will lead to decryption failure.

All changes from `v1alpha1` -> `v1alpha2` -> `v1alpha3` will lead to decryption faliures. Unfortunately - I think the only way to move between different versions of API is manual procedure, or semi automated. In gitops it is possible to scan the repository or multiple repositories and perform conversion of all the encrypted files via some shell script:
* decrypt to temp
* change fields which are changed from version to version (apiversion, any changes to the spec)
* reencrypt and commit (all while operator is disabled)

**Comment by travisghansen** [comment]
Yeah, good points about the decryption challenges.

In the CRD do you encrypt/store each secret separately or is the whole block treated as a big text string and encrypted?

I'll have to put some extra thought into this and see if I can dream anything up as well that might help.

**Comment by isindir** [comment]
I'm using `sops` tool as is to encrypt and when it does it - it encrypts whole document or can encrypt part of the yaml tree by filters like `--encrypted-suffix` and `--encrypted-regex`. I'm using ability of partial encryption to keep metadata as is, otherwise I'd not be able to apply to k8s api these objects. The idea was to encrypt only part of the spec, where actual secrets are defined, ie secret templates.

May be I can simplify migration job by adding old APIs to the the CRD mark them as deprecated but at least that would help you avoid manual manipulation of the CRD and it will include old version definitions forever ?

**Comment by travisghansen** [comment]
That would certainly help! I do manage my CRDs via gitops so being able to have both would be a helpful feature for sure. I'm not sure I would keep the old versions forever, but maybe the last N versions or something of that nature.

I'm still thinking through some of the other stuff FYI, just don't have any concrete thoughts yet.

**Comment by isindir** [comment]
@travisghansen #83 adds support for multiple CRDs (but only latest is stored in etcd), but I did not test the full procedure of upgrading with new CRD definition

**Comment by travisghansen** [comment]
Understood. So what happens to the old resources once the crd is applied? They’re still accessible right? But the controller will just ignore them as if nothing were there?

**Comment by isindir** [comment]
I would not rely on these, as storage is changed to only `v1alpha3` (only one version can be stored anyway). The procedure (not tested) would be:
* Scale down to 0 operator pods
* update CRD
* update all the `Sops` objects
* Re-deploy latest version of the operator scaled to original number of pods

All of the above operations can be performed via gitops.

Where `Sops` encrypted objects needs to be reconfigured via some script to the latest API version as:
* decrypt
* update version, `_templates` to `Templates`, `data` to `stringData`
* encrypt

**Comment by isindir** [comment]
I don't think this can and will be done - closing
