### ISSUE TITLE
Question about imagePullSecrets

### ISSUE THREAD

**Issue by gprasad84** [isindir/sops-secrets-operator#9]
Hi,

I am running into issues when I define `imagePullSecrets` using sops-secrets-operator. Even though I have defined a sopssecret of type `kubernetes.io/dockerconfigjson`, the kubelet on the cluster errors out saying it does not have permissions to pull images from the private registry. To verify its not an issue with the permissions, I directly created a K8s secret on the cluster(bypassing the sops secret operator) using kubectl and it seemed to pull the images just fine. I also noticed when the operator decrypts the secret into the cluster, it does not create a secret of type `kubernetes.io/dockerconfig.json` , instead it creates of type `Opaque`. Could this be an issue ?

**Comment by isindir** [comment]
I think that is a bug in the operator. Are you using operator with flux or standalone ?

**Comment by gprasad84** [comment]
Oh I see. Currently I am using this as a standalone with ArgoCD. Thanks for the update

**Comment by isindir** [comment]
Following should allow to create any type of k8s secret I found in k8s 1.18.2 code: https://github.com/isindir/sops-secrets-operator/pull/10/files

Example for docker config secret is in https://github.com/isindir/sops-secrets-operator/blob/master/deploy/crds/00init.yaml

Please try when it is merged and build and let me know if it works for you.

**Comment by gprasad84** [comment]
The new version worked ! Thanks for the fix.
