### ISSUE TITLE
Possible x509 enc/dec?

### ISSUE THREAD

**Issue by nwmcsween** [isindir/sops-secrets-operator#92]
This would helpful for step-ca integration and allow for more automation.

**Comment by isindir** [comment]
Hi @nwmcsween , atm this operator supports all the KMS options supported by Mozilla SOPS. Also, it would be better if you explain a bit better what you would like to achieve - how you see this new feature. Have you tried operator with [age](https://github.com/FiloSottile/age) + [sops](https://github.com/mozilla/sops) or other KMS ?

**Comment by nwmcsween** [comment]
The idea with this is step-ca could distribute keys via ADCS, etc to workstations and have passive revoke capability as well as having an MFA workflow for decryption/encryption if wanted. Instead of age or pgp and rolling your own authorization levels just use the IDP and certs, unless I'm missing something that pgp and age could do.

**Comment by nwmcsween** [comment]
mozilla/sops#797

**Comment by isindir** [comment]
@nwmcsween I must make it clear - this operator purpose is only to provide a way to store secrets encrypted in git code repository and then being created in Kubernetes cluster from that code repo. For this I'm using kubernetes [CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) so users can create encrypted CRs. Once CR is applied to the k8s cluster, controller decrypts its content using sops as library and creates managed k8s secret resources. CR itself is just k8s applicable yaml file encrypted with `sops` cli.

I'm still not exactly sure what are you trying to achieve, as:
- "distribute keys via ADCS, etc to workstations" - there are no workstations in k8s
- TLS CA can be achieved with tools like cert-manager , hashicorp vault and probably many more including service mesh solutions in k8s landscape, depending on requirements and use cases.

If your requirement is - use step-ca TLS material do decrypt data and create k8s secrets - this may be achievable by this operator with changes to `sops` and changes to the operator. Potentially possible to do without sops, but then I'd personaly  do it as a completely separate project.

If your requirement is different from the above - unlikely this operator should address it.

If you wish to discuss this, please contact me via keybase directly (link on my profile).

**Comment by isindir** [comment]
Closing this issue
