### ISSUE TITLE
Allow for multiple GPG keys

### ISSUE THREAD

**Issue by lfdominguez** [isindir/sops-secrets-operator#94]
Hi I want to use this great SOPS operator, but we are a sysadmin team and every sysadmin has their own Private Keys (and the public keys of all the team).
How can I add these privates keys to this operator to allow SOPS to decrypt the secret?

**Comment by isindir** [comment]
@lfdominguez , I think you don't need to have multiple private keys in operator configuration, instead - that should be a single private key (like now) whoch you treat as a system, but all k8s resources should be encrypted with recipients - users and system recipient. This is typical practice of encrypting with PGP. For that to work, each member of the team should have public keys of other members. It then becomes teams responsibility to manage the list of keys of all the members.

**Comment by lfdominguez** [comment]
well think on this.... sysadmin A and sysadmin B, A encrypt with their public Key the secret X, but then sysadmin B need to modify that secret X, so need the sysadmin A private key. We need avoid the private keys sharing.

**Comment by lfdominguez** [comment]
Underestand the method now... thanks.
